//
//  DPShaperLayerChainModel.m
//  DPCategory
//
//  Created by 麻小亮 on 2019/1/4.
//  Copyright © 2019 xllpp. All rights reserved.
//

#import "DPShaperLayerChainModel.h"
#define DPCATEGORY_CHAIN_SHAPERLAYER_IMPLEMENTATION(DPMethod,DPParaType) DPCATEGORY_CHAIN_LAYERCLASS_IMPLEMENTATION(DPMethod,DPParaType, DPShaperLayerChainModel *, CAShapeLayer)

@implementation DPShaperLayerChainModel
DPCATEGORY_CHAIN_SHAPERLAYER_IMPLEMENTATION(path, CGPathRef)
DPCATEGORY_CHAIN_SHAPERLAYER_IMPLEMENTATION(fillColor, CGColorRef)
DPCATEGORY_CHAIN_SHAPERLAYER_IMPLEMENTATION(fillRule, CAShapeLayerFillRule)
DPCATEGORY_CHAIN_SHAPERLAYER_IMPLEMENTATION(strokeColor, CGColorRef)
DPCATEGORY_CHAIN_SHAPERLAYER_IMPLEMENTATION(strokeStart, CGFloat)
DPCATEGORY_CHAIN_SHAPERLAYER_IMPLEMENTATION(strokeEnd, CGFloat)
DPCATEGORY_CHAIN_SHAPERLAYER_IMPLEMENTATION(lineWidth, CGFloat)
DPCATEGORY_CHAIN_SHAPERLAYER_IMPLEMENTATION(miterLimit, CGFloat)
DPCATEGORY_CHAIN_SHAPERLAYER_IMPLEMENTATION(lineCap, CAShapeLayerLineCap)
DPCATEGORY_CHAIN_SHAPERLAYER_IMPLEMENTATION(lineJoin, CAShapeLayerLineJoin)
DPCATEGORY_CHAIN_SHAPERLAYER_IMPLEMENTATION(lineDashPhase, CGFloat)
DPCATEGORY_CHAIN_SHAPERLAYER_IMPLEMENTATION(lineDashPattern, NSArray<NSNumber *> *)
@end
DPCATEGORY_LAYER_IMPLEMENTATION(CAShapeLayer, DPShaperLayerChainModel)
#undef DPCATEGORY_CHAIN_SHAPERLAYER_IMPLEMENTATION
