//
//  DPTextLayerChainModel.m
//  DPCategory
//
//  Created by 麻小亮 on 2019/1/4.
//  Copyright © 2019 xllpp. All rights reserved.
//

#import "DPTextLayerChainModel.h"
#define DPCATEGORY_CHAIN_TEXTLAYER_IMPLEMENTATION(DPMethod,DPParaType) DPCATEGORY_CHAIN_LAYERCLASS_IMPLEMENTATION(DPMethod,DPParaType, DPTextLayerChainModel *, CATextLayer)

@implementation DPTextLayerChainModel
DPCATEGORY_CHAIN_TEXTLAYER_IMPLEMENTATION(string, id)
DPCATEGORY_CHAIN_TEXTLAYER_IMPLEMENTATION(font, CFTypeRef)
DPCATEGORY_CHAIN_TEXTLAYER_IMPLEMENTATION(fontSize, CGFloat)
DPCATEGORY_CHAIN_TEXTLAYER_IMPLEMENTATION(foregroundColor, CGColorRef)
DPCATEGORY_CHAIN_TEXTLAYER_IMPLEMENTATION(wrapped, BOOL)
DPCATEGORY_CHAIN_TEXTLAYER_IMPLEMENTATION(truncationMode, CATextLayerTruncationMode)
DPCATEGORY_CHAIN_TEXTLAYER_IMPLEMENTATION(alignmentMode, CATextLayerAlignmentMode)
DPCATEGORY_CHAIN_TEXTLAYER_IMPLEMENTATION(allowsFontSubpixelQuantization, BOOL)

@end
DPCATEGORY_LAYER_IMPLEMENTATION(CATextLayer, DPTextLayerChainModel)
#undef DPCATEGORY_CHAIN_TEXTLAYER_IMPLEMENTATION
