//
//  DPTextViewChainModel.m
//  DPCategory
//
//  Created by 麻小亮 on 2018/12/27.
//  Copyright © 2018 xllpp. All rights reserved.
//

#import "DPTextViewChainModel.h"
#define DPCATEGORY_CHAIN_TEXT_IMPLEMENTATION(DPMethod,DPParaType) DPCATEGORY_CHAIN_VIEWCLASS_IMPLEMENTATION(DPMethod,DPParaType, DPTextViewChainModel *,UITextView)
@implementation DPTextViewChainModel
DPCATEGORY_CHAIN_TEXT_IMPLEMENTATION(delegate, id<UITextViewDelegate>);
DPCATEGORY_CHAIN_TEXT_IMPLEMENTATION(text, NSString *);
DPCATEGORY_CHAIN_TEXT_IMPLEMENTATION(font, UIFont *);
DPCATEGORY_CHAIN_TEXT_IMPLEMENTATION(textColor, UIColor *);
DPCATEGORY_CHAIN_TEXT_IMPLEMENTATION(textAlignment, NSTextAlignment);
DPCATEGORY_CHAIN_TEXT_IMPLEMENTATION(selectedRange, NSRange);
DPCATEGORY_CHAIN_TEXT_IMPLEMENTATION(editable, BOOL);
DPCATEGORY_CHAIN_TEXT_IMPLEMENTATION(selectable, BOOL);
DPCATEGORY_CHAIN_TEXT_IMPLEMENTATION(dataDetectorTypes, UIDataDetectorTypes);
DPCATEGORY_CHAIN_TEXT_IMPLEMENTATION(keyboardType, UIKeyboardType);
DPCATEGORY_CHAIN_TEXT_IMPLEMENTATION(allowsEditingTextAttributes, BOOL);
DPCATEGORY_CHAIN_TEXT_IMPLEMENTATION(attributedText, NSAttributedString *);
DPCATEGORY_CHAIN_TEXT_IMPLEMENTATION(typingAttributes, NSDictionary *);
DPCATEGORY_CHAIN_TEXT_IMPLEMENTATION(clearsOnInsertion, BOOL);
DPCATEGORY_CHAIN_TEXT_IMPLEMENTATION(textContainerInset, UIEdgeInsets);
DPCATEGORY_CHAIN_TEXT_IMPLEMENTATION(linkTextAttributes, NSDictionary *);
#pragma mark - UITextInputTraits -
DPCATEGORY_CHAIN_TEXT_IMPLEMENTATION(autocapitalizationType, UITextAutocapitalizationType);
DPCATEGORY_CHAIN_TEXT_IMPLEMENTATION(autocorrectionType, UITextAutocorrectionType)
DPCATEGORY_CHAIN_TEXT_IMPLEMENTATION(spellCheckingType, UITextSpellCheckingType)

DPCATEGORY_CHAIN_TEXT_IMPLEMENTATION(keyboardAppearance, UIKeyboardAppearance);
DPCATEGORY_CHAIN_TEXT_IMPLEMENTATION(returnKeyType, UIReturnKeyType);
DPCATEGORY_CHAIN_TEXT_IMPLEMENTATION(enablesReturnKeyAutomatically, BOOL);
DPCATEGORY_CHAIN_TEXT_IMPLEMENTATION(secureTextEntry, BOOL);
DPCATEGORY_CHAIN_TEXT_IMPLEMENTATION(textContentType, UITextContentType);
@end
DPCATEGORY_VIEW_IMPLEMENTATION(UITextView, DPTextViewChainModel)

#undef DPCATEGORY_CHAIN_TEXT_IMPLEMENTATION
