//
//  DPEmiiterLayerChainModel.m
//  DPCategory
//
//  Created by 麻小亮 on 2019/1/4.
//  Copyright © 2019 xllpp. All rights reserved.
//

#import "DPEmiiterLayerChainModel.h"
#define DPCATEGORY_CHAIN_EMITTERLAYER_IMPLEMENTATION(DPMethod,DPParaType) DPCATEGORY_CHAIN_LAYERCLASS_IMPLEMENTATION(DPMethod,DPParaType, DPEmiiterLayerChainModel *, CAEmitterLayer)

@implementation DPEmiiterLayerChainModel
DPCATEGORY_CHAIN_EMITTERLAYER_IMPLEMENTATION(emitterCells, NSArray<CAEmitterCell *> *)
DPCATEGORY_CHAIN_EMITTERLAYER_IMPLEMENTATION(birthRate, float)
DPCATEGORY_CHAIN_EMITTERLAYER_IMPLEMENTATION(lifetime, float)
DPCATEGORY_CHAIN_EMITTERLAYER_IMPLEMENTATION(emitterPosition, CGPoint)
DPCATEGORY_CHAIN_EMITTERLAYER_IMPLEMENTATION(emitterZPosition, CGFloat)
DPCATEGORY_CHAIN_EMITTERLAYER_IMPLEMENTATION(emitterSize, CGSize)
DPCATEGORY_CHAIN_EMITTERLAYER_IMPLEMENTATION(emitterDepth, CGFloat)

#ifdef __IPHONE_12_0
DPCATEGORY_CHAIN_EMITTERLAYER_IMPLEMENTATION(emitterShape, CAEmitterLayerEmitterShape)
DPCATEGORY_CHAIN_EMITTERLAYER_IMPLEMENTATION(emitterMode, CAEmitterLayerEmitterMode)
DPCATEGORY_CHAIN_EMITTERLAYER_IMPLEMENTATION(renderMode, CAEmitterLayerRenderMode)
#endif
DPCATEGORY_CHAIN_EMITTERLAYER_IMPLEMENTATION(preservesDepth, BOOL)
DPCATEGORY_CHAIN_EMITTERLAYER_IMPLEMENTATION(velocity, float)
DPCATEGORY_CHAIN_EMITTERLAYER_IMPLEMENTATION(scale, float)
DPCATEGORY_CHAIN_EMITTERLAYER_IMPLEMENTATION(spin, float)
DPCATEGORY_CHAIN_EMITTERLAYER_IMPLEMENTATION(seed, unsigned int)
@end
DPCATEGORY_LAYER_IMPLEMENTATION(CAEmitterLayer, DPEmiiterLayerChainModel)
#undef DPCATEGORY_CHAIN_EMITTERLAYER_IMPLEMENTATION
