//
//  DPReplicatorLayerChainModel.m
//  DPCategory
//
//  Created by 麻小亮 on 2019/1/4.
//  Copyright © 2019 xllpp. All rights reserved.
//

#import "DPReplicatorLayerChainModel.h"
#define DPCATEGORY_CHAIN_REPLICATORLAYER_IMPLEMENTATION(DPMethod,DPParaType) DPCATEGORY_CHAIN_LAYERCLASS_IMPLEMENTATION(DPMethod,DPParaType, DPReplicatorLayerChainModel *, CAReplicatorLayer)

@implementation DPReplicatorLayerChainModel
DPCATEGORY_CHAIN_REPLICATORLAYER_IMPLEMENTATION(instanceCount, NSInteger)
DPCATEGORY_CHAIN_REPLICATORLAYER_IMPLEMENTATION(preservesDepth, BOOL)
DPCATEGORY_CHAIN_REPLICATORLAYER_IMPLEMENTATION(instanceDelay, CFTimeInterval)
DPCATEGORY_CHAIN_REPLICATORLAYER_IMPLEMENTATION(instanceTransform, CATransform3D)
DPCATEGORY_CHAIN_REPLICATORLAYER_IMPLEMENTATION(instanceColor, CGColorRef)
DPCATEGORY_CHAIN_REPLICATORLAYER_IMPLEMENTATION(instanceRedOffset, float)
DPCATEGORY_CHAIN_REPLICATORLAYER_IMPLEMENTATION(instanceGreenOffset, float)
DPCATEGORY_CHAIN_REPLICATORLAYER_IMPLEMENTATION(instanceBlueOffset, float)
DPCATEGORY_CHAIN_REPLICATORLAYER_IMPLEMENTATION(instanceAlphaOffset, float)
@end
DPCATEGORY_LAYER_IMPLEMENTATION(CAReplicatorLayer, DPReplicatorLayerChainModel)
#undef DPCATEGORY_CHAIN_REPLICATORLAYER_IMPLEMENTATION
